# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ServiceExportConfigurationInfo(Model):
    """Export operation configuration information.

    :param storage_account_name: The name of the default export storage
     account.
    :type storage_account_name: str
    """

    _attribute_map = {
        'storage_account_name': {'key': 'storageAccountName', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(ServiceExportConfigurationInfo, self).__init__(**kwargs)
        self.storage_account_name = kwargs.get('storage_account_name', None)
